(function(){ function h(a){throw a;}var i=void 0,l=!0,m=null,n=!1,aa=encodeURIComponent,ba=Object,ca=Function,o=chrome,p=Array,da=localStorage,r=Error,ea=parseInt,fa=decodeURIComponent;function ga(a,b){return a.length=b}function ha(a,b){return a.target=b}
var t="push",v="tabs",ia="test",ja="slice",w="replace",ka="removed",x="indexOf",la="capture",ma="readyState",na="keyCode",oa="forEach",pa="handleEvent",y="type",qa="executeScript",sa="bind",ta="toString",z="length",ua="propertyIsEnumerable",A="prototype",va="removeEventListener",B="split",wa="target",C="call",D="apply",E="setIcon",F="browserAction",H="",xa=" ",ya='"',za="&",Aa="(",Ba="(\\d*)(\\D*)",Ca=")",Da=",",Ea="-",Fa=".",Ga=".js",Ha=".png",Ia="/inputtools/request",Ja="/request",Ka="0",La="00",
Ma="000",Na=":",Oa="=",Pa="@",Qa="Content-Type",Ra="MSXML2.XMLHTTP",Sa="MSXML2.XMLHTTP.3.0",Ta="MSXML2.XMLHTTP.6.0",Ua="Microsoft.XMLHTTP",Va="POST",Wa="[",Xa="[object Array]",Ya="[object Function]",Za="[object Window]",$a="\\u",ab="]",bb="_active",cb="_inactive",db="abort",eb="all",fb="application/x-www-form-urlencoded;charset=utf-8",I="array",gb="available",hb="boolean",ib="call",jb="chext_driver.js",kb="chext_inputtoolsbin.css",lb="chext_loader.js",J="complete",mb="current_input",nb="current_input_state",
ob="error",pb="event",K="function",qb="g",rb="he",sb="https://inputtools.google.com",tb="im_pinyin",ub="im_t13n_he",vb="im_t13n_iw",wb="image/",xb="image/active_flag.png",yb="image/inactive_flag.png",zb="image/vkd_active.png",Ab="input_tools",Bb="iw",Cb="layouts/",Db="native code",Eb="null",Fb="number",Gb="object",Hb="on",Ib="pt",Jb="pt-PT",Kb="pt-pt",Lb="ready",Mb="readystatechange",Nb="splice",Ob="string",Pb="success",Qb="update",Rb="vkd",Sb="vkd_deva_phone",Tb="vkd_he",Ub="vkd_iw",Vb="window",
Wb="withCredentials",Xb="zh",Yb="zh-Hans",Zb="zh-Hant",$b="zh-cn",ac="zh-hans",bc="{",cc="}",L;function dc(){}
function M(a){var b=typeof a;if(b==Gb)if(a){if(a instanceof p)return I;if(a instanceof ba)return b;var c=ba[A][ta][C](a);if(c==Za)return Gb;if(c==Xa||typeof a[z]==Fb&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[ua]&&!a[ua](Nb))return I;if(c==Ya||"undefined"!=typeof a[C]&&"undefined"!=typeof a[ua]&&!a[ua](ib))return K}else return Eb;else if(b==K&&"undefined"==typeof a[C])return Gb;return b}function ec(a){var b=M(a);return b==I||b==Gb&&typeof a[z]==Fb}function N(a){return typeof a==Ob}
function fc(a){return a[gc]||(a[gc]=++hc)}function ic(a,b,c){return a[C][D](a[sa],arguments)}function jc(a,b,c){a||h(r());if(2<arguments[z]){var d=p[A][ja][C](arguments,2);return function(){var c=p[A][ja][C](arguments);p[A].unshift[D](c,d);return a[D](b,c)}}return function(){return a[D](b,arguments)}}function O(a,b,c){O=ca[A][sa]&&-1!=ca[A][sa][ta]()[x](Db)?ic:jc;return O[D](m,arguments)}function kc(a,b){function c(){}c.prototype=b[A];a.u=b[A];a.prototype=new c}
function lc(a,b){var c=mc(a,b);0<=c&&P.splice[C](a,c,1)}function nc(a){return P.concat[D](P,arguments)}function oc(a){var b=a[z];if(0<b){for(var c=p(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function pc(a){a=H+a;if(/^\s*$/[ia](a)?0:/^[\],:{}\s\u2028\u2029]*$/[ia](a[w](/\\["\\\/bfnrtu]/g,Pa)[w](/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,ab)[w](/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,H)))try{return eval(Aa+a+Ca)}catch(b){}h(r("Invalid JSON string: "+a))}function qc(a){var b=[];rc(new sc,a,b);return b.join(H)}function sc(){this.a=i}
function rc(a,b,c){switch(typeof b){case Ob:tc(b,c);break;case Fb:c[t](isFinite(b)&&!isNaN(b)?b:Eb);break;case hb:c[t](b);break;case "undefined":c[t](Eb);break;case Gb:if(b==m){c[t](Eb);break}if(M(b)==I){var d=b[z];c[t](Wa);for(var e=H,f=0;f<d;f++)c[t](e),e=b[f],rc(a,a.a?a.a[C](b,H+f,e):e,c),e=Da;c[t](ab);break}c[t](bc);d=H;for(f in b)ba[A].hasOwnProperty[C](b,f)&&(e=b[f],typeof e!=K&&(c[t](d),tc(f,c),c[t](Na),rc(a,a.a?a.a[C](b,f,e):e,c),d=Da));c[t](cc);break;case K:break;default:h(r("Unknown type: "+
typeof b))}}function tc(a,b){b[t](ya,a[w](uc,function(a){if(a in vc)return vc[a];var b=a.charCodeAt(0),e=$a;16>b?e+=Ma:256>b?e+=La:4096>b&&(e+=Ka);return vc[a]=e+b[ta](16)}),ya)}function wc(){}function xc(a,b,c){for(var d in a)b[C](c,a[d],d,a)}function yc(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function zc(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ac(a){for(var b in a)return n;return l}
function Bc(a,b){for(var c,d,e=1;e<arguments[z];e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Cc[z];f++)c=Cc[f],ba[A].hasOwnProperty[C](d,c)&&(a[c]=d[c])}}function Dc(a){if(typeof a.h==K)return a.h();if(N(a))return a[B](H);if(ec(a)){for(var b=[],c=a[z],d=0;d<c;d++)b[t](a[d]);return b}return yc(a)}function Ec(a){if(typeof a.n==K)return a.n();if(typeof a.h!=K){if(ec(a)||N(a)){for(var b=[],a=a[z],c=0;c<a;c++)b[t](c);return b}return zc(a)}}
function Fc(a,b){this.b={};this.a=[];var c=arguments[z];if(1<c){c%2&&h(r("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Fc?(c=a.n(),d=a.h()):(c=zc(a),d=yc(a));for(var e=0;e<c[z];e++)this.set(c[e],d[e])}}function Gc(a){if(a.d!=a.a[z]){for(var b=0,c=0;b<a.a[z];){var d=a.a[b];Q(a.b,d)&&(a.a[c++]=d);b++}ga(a.a,c)}if(a.d!=a.a[z]){for(var e={},c=b=0;b<a.a[z];)d=a.a[b],Q(e,d)||(a.a[c++]=d,e[d]=1),b++;ga(a.a,c)}}
function Q(a,b){return ba[A].hasOwnProperty[C](a,b)}function Hc(){return R.navigator?R.navigator.userAgent:m}
function S(a){var b;if(!(b=Ic[a])){b=0;for(var c=(H+Kc)[w](/^[\s\xa0]+|[\s\xa0]+$/g,H)[B](Fa),d=(H+a)[w](/^[\s\xa0]+|[\s\xa0]+$/g,H)[B](Fa),e=Math.max(c[z],d[z]),f=0;0==b&&f<e;f++){var g=c[f]||H,k=d[f]||H,j=RegExp(Ba,qb),u=RegExp(Ba,qb);do{var s=j.exec(g)||[H,H,H],q=u.exec(k)||[H,H,H];if(0==s[0][z]&&0==q[0][z])break;b=((0==s[1][z]?0:ea(s[1],10))<(0==q[1][z]?0:ea(q[1],10))?-1:(0==s[1][z]?0:ea(s[1],10))>(0==q[1][z]?0:ea(q[1],10))?1:0)||((0==s[2][z])<(0==q[2][z])?-1:(0==s[2][z])>(0==q[2][z])?1:0)||(s[2]<
q[2]?-1:s[2]>q[2]?1:0)}while(0==b)}b=Ic[a]=0<=b}return b}function Lc(){return Mc[9]||(Mc[9]=T&&!!document.documentMode&&9<=document.documentMode)}function Nc(){}function Oc(a){for(var b=0,c=arguments[z];b<c;++b){var d=arguments[b];ec(d)?Oc[D](m,d):d&&typeof d.v==K&&d.v()}}function Pc(a){Pc[xa](a);return a}function U(a,b){this.type=a;ha(this,b);this.a=this[wa]}function V(a,b){a&&Qc(this,a,b)}
function Qc(a,b,c){var d=a.type=b[y];U[C](a,d);ha(a,b[wa]||b.srcElement);a.a=c;if((c=b.relatedTarget)&&Rc)try{Pc(c.nodeName)}catch(e){}a.l=b;b.defaultPrevented&&a.p();delete a.b}function Sc(){}
function Tc(a,b,c,d,e){if(b)if(M(b)==I)for(var f=0;f<b[z];f++)Tc(a,b[f],c,d,e);else{var d=!!d,g=X;b in g||(g[b]={d:0,f:0});g=g[b];d in g||(g[d]={d:0,f:0},g.d++);var g=g[d],k=fc(a),j;g.f++;if(g[k]){j=g[k];for(f=0;f<j[z];f++)if(g=j[f],g.q==c&&g.G==e){if(g[ka])break;return}}else j=g[k]=[],g.d++;var u=Uc,s=Vc?function(a){return u[C](s.src,s.key,a)}:function(a){a=u[C](s.src,s.key,a);if(!a)return a},f=s;f.src=a;var q=g=new Sc;M(c)==K?q.b=l:c&&c[pa]&&M(c[pa])==K?q.b=n:h(r("Invalid listener argument"));q.q=
c;q.proxy=f;q.src=a;q.type=b;q.capture=!!d;q.G=e;q.a=n;q.key=++Wc;q.removed=n;c=g.key;f.key=c;j[t](g);Xc[c]=g;Y[k]||(Y[k]=[]);Y[k][t](g);a.addEventListener?(a==R||!a.K)&&a.addEventListener(b,f,d):a.attachEvent(b in Yc?Yc[b]:Yc[b]=Hb+b,f)}else h(r("Invalid event type"))}
function Zc(a,b,c,d,e){if(M(b)==I)for(var f=0;f<b[z];f++)Zc(a,b[f],c,d,e);else{d=!!d;a:{f=X;if(b in f&&(f=f[b],d in f&&(f=f[d],a=fc(a),f[a]))){a=f[a];break a}a=m}if(a)for(f=0;f<a[z];f++)if(a[f].q==c&&a[f][la]==d&&a[f].G==e){$c(a[f].key);break}}}
function $c(a){if(Xc[a]){var b=Xc[a];if(!b[ka]){var c=b.src,d=b[y],e=b.proxy,f=b[la];c[va]?(c==R||!c.K)&&c[va](d,e,f):c.detachEvent&&c.detachEvent(d in Yc?Yc[d]:Yc[d]=Hb+d,e);c=fc(c);e=X[d][f][c];if(Y[c]){var g=Y[c];lc(g,b);0==g[z]&&delete Y[c]}b.removed=l;e.M=l;ad(d,f,c,e);delete Xc[a]}}}
function ad(a,b,c,d){if(!d.A&&d.M){for(var e=0,f=0;e<d[z];e++)d[e][ka]?d[e].proxy.src=m:(e!=f&&(d[f]=d[e]),f++);ga(d,f);d.M=n;0==f&&(delete X[a][b][c],X[a][b].d--,0==X[a][b].d&&(delete X[a][b],X[a].d--),0==X[a].d&&delete X[a])}}function bd(a,b,c,d,e){var f=1,b=fc(b);if(a[b]){a.f--;a=a[b];a.A?a.A++:a.A=1;try{for(var g=a[z],k=0;k<g;k++){var j=a[k];j&&!j[ka]&&(f&=cd(j,e)!==n)}}finally{a.A--,ad(c,d,b,a)}}return Boolean(f)}function cd(a,b){a.a&&$c(a.key);return a[pa](b)}
function Uc(a,b){if(!Xc[a])return l;var c=Xc[a],d=c[y],e=X;if(!(d in e))return l;var e=e[d],f,g;if(!Vc){var k;if(!(k=b))a:{k=[Vb,pb];for(var j=R;f=k.shift();)if(j[f]!=m)j=j[f];else{k=m;break a}k=j}f=k;k=l in e;j=n in e;if(k){if(0>f[na]||f.returnValue!=i)return l;a:{var u=n;if(0==f[na])try{f.keyCode=-1;break a}catch(s){u=l}if(u||f.returnValue==i)f.returnValue=l}}u=new V;Qc(u,f,this);f=l;try{if(k){for(var q=[],ra=u.a;ra;ra=ra.parentNode)q[t](ra);g=e[l];g.f=g.d;for(var G=q[z]-1;!u.b&&0<=G&&g.f;G--)u.a=
q[G],f&=bd(g,q[G],d,l,u);if(j){g=e[n];g.f=g.d;for(G=0;!u.b&&G<q[z]&&g.f;G++)u.a=q[G],f&=bd(g,q[G],d,n,u)}}else f=cd(c,u)}finally{q&&ga(q,0),u.v()}return f}d=new V(b,this);try{f=cd(c,d)}finally{d.v()}return f}function dd(){}
function Z(a,b){var c=b,d=c[y]||c,e=X;if(d in e){if(N(c))c=new U(c,a);else if(c instanceof U)ha(c,c[wa]||a);else{var f=c,c=new U(d,a);Bc(c,f)}var f=1,g,e=e[d],d=l in e,k;if(d){g=[];for(k=a;k;k=k.F)g[t](k);k=e[l];k.f=k.d;for(var j=g[z]-1;!c.b&&0<=j&&k.f;j--)c.a=g[j],f&=bd(k,g[j],c[y],l,c)&&c.g!=n}if(n in e)if(k=e[n],k.f=k.d,d)for(j=0;!c.b&&j<g[z]&&k.f;j++)c.a=g[j],f&=bd(k,g[j],c[y],n,c)&&c.g!=n;else for(e=a;!c.b&&e&&k.f;e=e.F)c.a=e,f&=bd(k,e,c[y],n,c)&&c.g!=n}}
function ed(a,b){if(fd){fd=n;var c=R.location;if(c){var d=c.href;if(d&&(d=(d=ed(3,d))&&fa(d))&&d!=c.hostname)fd=l,h(r())}}return b.match(gd)[a]||m}function hd(){}function id(){}function jd(a){return(a=kd(a))?new ActiveXObject(a):new XMLHttpRequest}function ld(a){var b={};kd(a)&&(b[0]=l,b[1]=l);return b}
function kd(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=[Ta,Sa,Ra,Ua],c=0;c<b[z];c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}h(r("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.b}function md(a){this.b=new Fc;this.a=a||m}function nd(a){a.i=n;a.c&&(a.k=l,a.c.abort(),a.k=n);od(a);pd(a)}function od(a){a.D||(a.D=l,Z(a,J),Z(a,ob))}
function qd(a){a.c&&a.i&&(a.i=n,a.k=l,a.c.abort(),a.k=n,Z(a,J),Z(a,db),pd(a))}function rd(a){if(a.i&&"undefined"!=typeof sd&&(!a.t[1]||!(4==(a.c?a.c[ma]:0)&&2==td(a))))if(a.r&&4==(a.c?a.c[ma]:0))ud.setTimeout(O(a.H,a),0);else if(Z(a,Mb),4==(a.c?a.c[ma]:0)){a.i=n;try{a.L()?(Z(a,J),Z(a,Pb)):od(a)}finally{pd(a)}}}function pd(a,b){if(a.c){var c=a.c,d=a.t[0]?dc:m;a.c=m;a.t=m;a.m&&(ud.clearTimeout(a.m),a.m=m);b||Z(a,Lb);try{c.onreadystatechange=d}catch(e){}}}
function td(a){try{return 2<(a.c?a.c[ma]:0)?a.c.status:-1}catch(b){return-1}}function vd(a,b,c){this.a=a||m;this.b=!!c}function wd(a){if(!a.e&&(a.e=new Fc,a.d=0,a.a))for(var b=a.a[B](za),c=0;c<b[z];c++){var d=b[c][x](Oa),e=m,f=m;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=fa(e[w](/\+/g,xa));e=$(a,e);xd(a,e,f?fa(f[w](/\+/g,xa)):H)}}function xd(a,b,c){wd(a);a.a=m;var b=$(a,b),d=a.e.get(b);d||a.e.set(b,d=[]);d[t](c);a.d++}function yd(a,b){wd(a);b=$(a,b);return Q(a.e.b,b)}
function $(a,b){var c=H+b;a.b&&(c=c.toLowerCase());return c}function zd(){}function Ad(){}function Bd(a,b){da&&(da[a]=b)}function Cd(a){if(da){if(a=da.getItem(a))a=a[w](Ub,Tb),a=a[w](vb,ub);return a}}
function Dd(){this.a=new md;this.b=m;this.o={};this.g=0;Ed||(Ed=new Ad);Fd||(Fd=new zd);this.l=H;Cd(Ab)||Bd(Ab,H);var a=Gd();if(a){var b=Hd(),c=l;b?c=b.tlang||b.tlang==i:Id();o[F][E]({path:Jd(a,c)})}else Bd(mb,H),o[F][E]({path:xb});o.windows.getAll({populate:l},function(a){for(var b=0;b<a[z];b++)for(var c=a[b],g=0;g<c[v][z];g++)o[v][qa](c[v][g].id,{file:lb})});o.extension.onRequest.addListener(O(this.z,this))}
function Kd(a){o.windows.getAll({populate:l},function(b){for(var c=0;c<b[z];c++)for(var d=b[c],e=0;e<d[v][z];e++)o[v].sendRequest(d[v][e].id,a)})}function Ld(){var a=Cd(Ab),b=[];a&&(b=a[B](Da));return b}function Gd(){return Cd(mb)}function Hd(){var a=Cd(nb);return pc(a)}function Id(){Bd(nb,qc({}))}function Jd(a,b){if(0==a[x](Rb))return b?zb:yb;var c=wb,c=0==a[x](tb)?c+tb:c+a;return c+(b?bb:cb)+Ha}
function Md(a,b){var c=Gd();c!=b&&(a.l=c,Bd(mb,b),Id(),b?(Kd({current_input:b}),o[F][E]({path:Jd(b,l)})):(Kd({unset:eb}),o[F][E]({path:yb})))}var sd=sd||{},R=this,gc="closure_uid_"+Math.floor(2147483648*Math.random())[ta](36),hc=0;ca[A].bind=ca[A][sa]||function(a,b){if(1<arguments[z]){var c=p[A][ja][C](arguments,1);c.unshift(this,a);return O[D](m,c)}return O(this,a)};var P=p[A],mc=P[x]?function(a,b,c){return P[x][C](a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a[z]+c):c;if(N(a))return!N(b)||1!=b[z]?-1:a[x](b,c);for(;c<a[z];c++)if(c in a&&a[c]===b)return c;return-1},Nd=P[oa]?function(a,b,c){P[oa][C](a,b,c)}:function(a,b,c){for(var d=a[z],e=N(a)?a[B](H):a,f=0;f<d;f++)f in e&&b[C](c,e[f],f,a)};var vc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},uc=/\uffff/[ia]("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Od="StopIteration"in R?R.StopIteration:r("StopIteration");wc[A].next=function(){h(Od)};wc[A].R=function(){return this};var Cc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");L=Fc[A];L.d=0;L.w=0;L.h=function(){Gc(this);for(var a=[],b=0;b<this.a[z];b++)a[t](this.b[this.a[b]]);return a};L.n=function(){Gc(this);return this.a.concat()};L.remove=function(a){return Q(this.b,a)?(delete this.b[a],this.d--,this.w++,this.a[z]>2*this.d&&Gc(this),l):n};L.get=function(a,b){return Q(this.b,a)?this.b[a]:b};L.set=function(a,b){Q(this.b,a)||(this.d++,this.a[t](a),this.w++);this.b[a]=b};L.C=function(){return new Fc(this)};
L.R=function(a){Gc(this);var b=0,c=this.a,d=this.b,e=this.w,f=this,g=new wc;g.next=function(){for(;;){e!=f.w&&h(r("The map has changed since the iterator was created"));b>=c[z]&&h(Od);var g=c[b++];return a?g:d[g]}};return g};var Pd,Qd,Rd,Sd;Sd=Rd=Qd=Pd=n;var Td;if(Td=Hc()){var Ud=R.navigator;Pd=0==Td[x]("Opera");Qd=!Pd&&-1!=Td[x]("MSIE");Rd=!Pd&&-1!=Td[x]("WebKit");Sd=!Pd&&!Rd&&"Gecko"==Ud.product}var Vd=Pd,T=Qd,Rc=Sd,Wd=Rd,Xd;
a:{var Yd=H,Zd;if(Vd&&R.opera)var $d=R.opera.version,Yd=typeof $d==K?$d():$d;else if(Rc?Zd=/rv\:([^\);]+)(\)|;)/:T?Zd=/MSIE\s+([^\);]+)(\)|;)/:Wd&&(Zd=/WebKit\/(\S+)/),Zd)var ae=Zd.exec(Hc()),Yd=ae?ae[1]:H;if(T){var be,ce=R.document;be=ce?ce.documentMode:i;if(be>parseFloat(Yd)){Xd=H+be;break a}}Xd=Yd}var Kc=Xd,Ic={},Mc={};Nc[A].s=n;Nc[A].v=function(){this.s||(this.s=l,this.j())};Nc[A].j=function(){this.Q&&Oc[D](m,this.Q);if(this.z)for(;this.z[z];)this.z.shift()()};Pc[xa]=dc;!T||Lc();var Vc=!T||Lc(),de=T&&!S("8");!Wd||S("528");Rc&&S("1.9b")||T&&S("8")||Vd&&S("9.5")||Wd&&S("528");Rc&&!S("8")||T&&S("9");kc(U,Nc);U[A].j=function(){delete this[y];delete this[wa];delete this.a};U[A].b=n;U[A].g=l;U[A].p=function(){this.g=n};kc(V,U);ha(V[A],m);V[A].l=m;V[A].p=function(){V.u.p[C](this);var a=this.l;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,de)try{if(a.ctrlKey||112<=a[na]&&123>=a[na])a.keyCode=-1}catch(b){}};V[A].j=function(){V.u.j[C](this);this.l=m;ha(this,m);this.a=m};var Wc=0;Sc[A].key=0;Sc[A].removed=n;Sc[A].a=n;Sc[A].handleEvent=function(a){return this.b?this.q[C](this.G||this.src,a):this.q[pa][C](this.q,a)};var Xc={},X={},Y={},Yc={};kc(dd,Nc);L=dd[A];L.K=l;L.F=m;L.addEventListener=function(a,b,c,d){Tc(this,a,b,c,d)};L.removeEventListener=function(a,b,c,d){Zc(this,a,b,c,d)};L.j=function(){dd.u.j[C](this);var a,b=0,c=a==m;a=!!a;if(this==m)xc(Y,function(d){for(var e=d[z]-1;0<=e;e--){var f=d[e];if(c||a==f[la])$c(f.key),b++}});else{var d=fc(this);if(Y[d])for(var d=Y[d],e=d[z]-1;0<=e;e--){var f=d[e];if(c||a==f[la])$c(f.key),b++}}this.F=m};var ud=R.window;var gd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),fd=Wd;hd[A].a=m;var ee;kc(id,hd);ee=new id;kc(md,dd);var fe=/^https?$/i;L=md[A];L.i=n;L.c=m;L.t=m;L.I=H;L.D=n;L.r=n;L.B=n;L.k=n;L.m=m;L.J=H;L.N=n;L.j=function(){this.c&&(this.i&&(this.i=n,this.k=l,this.c.abort(),this.k=n),pd(this,l));md.u.j[C](this)};L.H=function(){!this.B&&!this.r&&!this.k?this.O():rd(this)};L.O=function(){rd(this)};
L.L=function(){var a=td(this),b;a:switch(a){case 200:case 201:case 202:case 204:case 304:case 1223:b=l;break a;default:b=n}if(!b){if(a=0===a)a=ed(1,H+this.I),!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a[z]-1)),a=!fe[ia](a?a.toLowerCase():H);b=a}return b};L=vd[A];L.e=m;L.d=m;L.remove=function(a){wd(this);a=$(this,a);return Q(this.e.b,a)?(this.a=m,this.d-=this.e.get(a)[z],this.e.remove(a)):n};L.n=function(){wd(this);for(var a=this.e.h(),b=this.e.n(),c=[],d=0;d<b[z];d++)for(var e=a[d],f=0;f<e[z];f++)c[t](b[d]);return c};L.h=function(a){wd(this);var b=[];if(a)yd(this,a)&&(b=nc(b,this.e.get($(this,a))));else for(var a=this.e.h(),c=0;c<a[z];c++)b=nc(b,a[c]);return b};
L.set=function(a,b){wd(this);this.a=m;a=$(this,a);yd(this,a)&&(this.d-=this.e.get(a)[z]);this.e.set(a,[b]);this.d++;return this};L.get=function(a,b){var c=a?this.h(a):[];return 0<c[z]?c[0]:b};L.toString=function(){if(this.a)return this.a;if(!this.e)return H;for(var a=[],b=this.e.n(),c=0;c<b[z];c++)for(var d=b[c],e=aa(H+d),d=this.h(d),f=0;f<d[z];f++){var g=e;d[f]!==H&&(g+=Oa+aa(H+d[f]));a[t](g)}return this.a=a.join(za)};L.C=function(){var a=new vd;a.a=this.a;this.e&&(a.e=this.e.C());return a};var Fd=m,ge={am:["vkd_ethi","im_t13n_am"],ar:["vkd_ar","im_t13n_ar"],be:["vkd_be","im_t13n_be"],bg:["vkd_bg","im_t13n_bg"],bn:["vkd_bn_phone","im_t13n_bn"],bs:["vkd_bs"],ca:["vkd_ca"],chr:["vkd_chr"],cs:["vkd_cs","vkd_cs_qwertz"],da:["vkd_da"],de:["vkd_de"],el:["vkd_el","im_t13n_el"],es:["vkd_es_es"],et:["vkd_et"],eu:["vkd_eu"],fa:["vkd_fa","im_t13n_fa"],fi:["vkd_fi"],fr:["vkd_fr"],gl:["vkd_gl"],gu:["vkd_gu_phone","im_t13n_gu"],hi:["vkd_hi",Sb,"im_t13n_hi"],hr:["vkd_hr"],hu:["vkd_hu_101"],hy:["vkd_hy_east",
"vkd_hy_west"],is:["vkd_is"],it:["vkd_it"],he:[Tb,ub],ja:["im_t13n_ja"],ka:["vkd_ka_qwerty","vkd_ka_typewriter"],kk:["vkd_kk"],km:["vkd_km"],kn:["vkd_kn_phone","im_t13n_kn"],ko:["vkd_ko"],ky:["vkd_ky_cyrl"],lo:["vkd_lo"],lt:["vkd_lt"],lv:["vkd_lv"],mk:["vkd_mk"],ml:["vkd_ml_phone","im_t13n_ml"],mn:["vkd_mn_cyrl"],mr:[Sb,"im_t13n_mr"],mt:["vkd_mt"],ne:[Sb,"im_t13n_ne"],nl:["vkd_nl"],no:["vkd_no"],or:["vkd_or_phone","im_t13n_or"],pa:["vkd_guru_phone","im_t13n_pa"],pl:["vkd_pl"],ps:["vkd_ps"],pt:["vkd_pt_br"],
"pt-PT":["vkd_pt_pt"],ro:["vkd_ro"],rom:["vkd_rom"],ru:["vkd_ru","im_t13n_ru"],sa:["vkd_sa_phone","im_t13n_sa"],si:["vkd_si","im_t13n_si"],sk:["vkd_sk","vkd_sk_qwerty"],sl:["vkd_sl"],sq:["vkd_sq"],sr:["vkd_sr_cyrl","vkd_sr_latn","im_t13n_sr"],srp:["vkd_srp"],sv:["vkd_sv"],ta:["vkd_ta_phone","im_t13n_ta"],te:["vkd_te_phone","im_t13n_te"],th:["vkd_th"],ti:["vkd_ethi","im_t13n_ti"],tr:["vkd_tr_f","vkd_tr_q"],tt:["vkd_tt"],ug:["vkd_ug"],uk:["vkd_uk_101","im_t13n_uk"],ur:["vkd_ur","im_t13n_ur"],uz:["vkd_uz_latn",
"vkd_uz_cyrl_phone","vkd_uz_cyrl_type"],vi:["im_t13n_vi","vkd_vi_tcvn","vkd_vi_telex","vkd_vi_viqr"],"zh-Hans":["im_pinyin_zh_hans","im_wubi_zh_hans"],"zh-Hant":["im_zhuyin_zh_hant","im_pinyin_zh_hant"]};var Ed=m;Dd[A].s=function(a,b){var c=b[wa],d=c.L()&&0!=td(c),e;if(d)try{e=c.c?c.c.responseText:H}catch(f){e=H}else e=m;c[va](J,this.b,l);a({isSuccess:d,responseText:e})};
Dd[A].z=function(a,b,c){if(a.get_prefs){var d=Ld(),e=Gd(),f=Hd();c({current_input:e,input_tools:d,current_input_states:f})}if(a.get_input_tools){var g;var e=a.get_input_tools,d=Ld(),k;e=e.toLowerCase();f=e[x](Ea);0>f?e=e==Ib?Jb:e==rb?Bb:e:(f=e[ja](0,f),e=f==Xb?e==$b||e==ac?Yb:Zb:f==Ib&&e==Kb?Jb:f);if((k=ge[e])&&0!=k[z])Nd(d,function(a){lc(k,a)}),g={detected_inputs:k};c(g)}a.add_input_tools&&(g=a.add_input_tools,d=Cd(Ab),Bd(Ab,g+(d?Da+d:H)),Kd({update:Qb}));if(a.im_send_request){g=a.url;f=a.payload;
this.a.c&&(qd(this.a),this.a[va](J,this.b,l),this.b=m);if(f){d=Ec(f);"undefined"==typeof d&&h(r("Keys are undefined"));for(var e=new vd(m,0,i),f=Dc(f),j=0;j<d[z];j++){var u=d[j],s=f[j];if(M(s)==I){var q=e;q.remove(u);0<s[z]&&(q.a=m,q.e.set($(q,u),oc(s)),q.d+=s[z])}else xd(e,u,s)}d=e[ta]()}else d=H;e=d;this.b=O(this.s,this,c);this.a.addEventListener(J,this.b,l);g=g[w](Ia,Ja);a:{d=this.a;g=sb+g;d.c&&h(r("[goog.net.XhrIo] Object is active with another request"));d.I=g;d.D=n;d.i=l;d.c=d.a?jd(d.a):jd(ee);
d.t=d.a?d.a.a||(d.a.a=ld(d.a)):ee.a||(ee.a=ld(ee));d.c.onreadystatechange=O(d.H,d);try{d.B=l,d.c.open(Va,g,l),d.B=n}catch(ra){nd(d);break a}g=e||H;j=d.b.C();!Q(j.b,Qa)&&j.set(Qa,fb);e=function(a,b){this.c.setRequestHeader(b,a)};if(typeof j[oa]==K)j[oa](e,d);else if(ec(j)||N(j))Nd(j,e,d);else{f=Ec(j);j=Dc(j);q=j[z];for(s=0;s<q;s++)e[C](d,j[s],f&&f[s])}d.J&&(d.c.responseType=d.J);Wb in d.c&&(d.c.withCredentials=d.N);try{d.m&&(ud.clearTimeout(d.m),d.m=m),d.r=l,d.c.send(g),d.r=n}catch(G){nd(d)}}}a.im_abort_request&&
qd(this.a);a.unset_current_input&&Md(this,H);a.set_current_input&&Md(this,a.set_current_input);if(a.set_current_input_state&&(g=a.set_current_input_state,d=a.init,e=Hd(),!d||!e||Ac(e))){for(var W in g)e[W]==g[W]&&W in g&&delete g[W];if(!Ac(g)){var Jc=Hd();xc(g,function(a,b){Jc[b]=a});Bd(nb,qc(Jc));W=Gd();Kd({current_input:W,current_input_states:g});g.tlang!=i&&o[F][E]({path:Jd(W,g.tlang)})}}a.revert_inputtool&&Md(this,this.l);a.get_layout&&o[v][qa](b.tab.id,{file:Cb+a.get_layout+Ga});a.update_all&&
(Kd({update:Qb}),Gd()||o[F][E]({path:yb}));a.request_available&&c(gb);a.load_driver&&(0<=b.tab.index?(o[v].insertCSS(b.tab.id,{file:kb}),o[v][qa](b.tab.id,{file:jb})):(a=this.o,b=b.tab.id,b in a&&h(r('The object already contains the key "'+b+ya)),a[b]=0,this.g||(this.g=window.setInterval(O(this.p,this),100))))};Dd[A].p=function(){Ac(this.o)?(window.clearInterval(this.g),this.g=0):xc(this.o,function(a,b,c){1E3<a?(a=this.o,b in a&&delete a[b]):(c[b]++,o[v].get(ea(b),O(this.P,this)))},this)};
Dd[A].P=function(a){if(0<=a.index){o[v].insertCSS(a.id,{file:kb});o[v][qa](a.id,{file:jb});var b=this.o,a=a.id;a in b&&delete b[a]}};new Dd; })()
